### ISSUE TITLE
Shared fbs between multiple projects

### ISSUE THREAD

**Issue by duckdoom4** [jamescourtney/FlatSharp#388]
I'd like to be able to share some code between multiple projects. For example:

We have Project A, Project B, Shared Project and Main Project.

Project A and Project B produce a dll consumed by Main Project.
Shared Project contains common fbs files that are shared between A and B.

Project A contains fbs files that need to include Shared project's fbs files.

Currently this doesn't seem to work. I get errors telling me that The type 'SharedType' in 'path\to\ProjectA\FlatSharp.generated.cs' conflicts with the imported type 'SharedType' in 'SharedProject, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'path\to\ProjectA\FlatSharp.generated.cs'.

To paint a better picture of our use case here are the details:

I have an fbs for vec3f, this is used in A and B.

```C#
namespace pkNX.Structures.FlatBuffers;

table Vec3f {
    X:float;
    Y:float;
    Z:float;
}
```

Then I implement the code (something like this):
```C#
namespace pkNX.Structures.FlatBuffers;

[TypeConverter(typeof(ExpandableObjectConverter))]
public partial class Vec3f
{
    public static readonly Vec3f Zero = new();
    public static readonly Vec3f One = new(1, 1, 1);

    public Vec3f(float x = 0, float y = 0, float z = 0)
    {
        X = x;
        Y = y;
        Z = z;
    }

    public bool IsOne => X is 1 && Y is 1 && Z is 1;
    public bool IsZero => X is 0 && Y is 0 && Z is 0;

    public float Magnitude => MathF.Sqrt(MagnitudeSqr);
    public float MagnitudeSqr => Dot(this);
    public Vec3f Normalized() => this * (1 / Magnitude);

    public float Dot(Vec3f other) => X * other.X + Y * other.Y + Z * other.Z;
    public Vec3f Cross(Vec3f other) => new(Y * other.Z - Z * other.Y, Z * other.X - X * other.Z, X * other.Y - Y * other.X);
    public float DistanceTo(Vec3f other) => (this - other).Magnitude;
    public float DistanceToSqr(Vec3f other) => (this - other).MagnitudeSqr;
    public Vec3f Lerp(Vec3f other, float t) => this + (other - this) * t;
    public static Vec3f operator -(Vec3f v) => new(-v.X, -v.Y, -v.Z);

    public static Vec3f operator +(Vec3f l, Vec3f r) => new(l.X + r.X, l.Y + r.Y, l.Z + r.Z);
    public static Vec3f operator -(Vec3f l, Vec3f r) => new(l.X - r.X, l.Y - r.Y, l.Z - r.Z);
    public static Vec3f operator *(Vec3f l, Vec3f r) => new(l.X * r.X, l.Y * r.Y, l.Z * r.Z);
    public static Vec3f operator /(Vec3f l, Vec3f r) => new(l.X / r.X, l.Y / r.Y, l.Z / r.Z);

    public static Vec3f operator +(Vec3f l, float r) => new(l.X + r, l.Y + r, l.Z + r);
    public static Vec3f operator -(Vec3f l, float r) => new(l.X - r, l.Y - r, l.Z - r);
    public static Vec3f operator *(Vec3f l, float r) => new(l.X * r, l.Y * r, l.Z * r);
    public static Vec3f operator /(Vec3f l, float r) => new(l.X / r, l.Y / r, l.Z / r);

    public static bool operator ==(Vec3f? left, Vec3f? right) => Equals(left, right);
    public static bool operator !=(Vec3f? left, Vec3f? right) => !Equals(left, right);
}
```
Now project A and B will use the above mentioned code/fbs include from the shared project.

As of right now, this wouldn't work. Due to the errors mentioned earlier. I hope this paints a better picture, if not I can make a sample project.

**Comment by jamescourtney** [comment]
Congrats! You've broken FlatSharp in a way I never anticipated or even really considered :) Looks like you're running afoul of [this](https://stackoverflow.com/questions/3205027/maximum-length-of-command-line-string). FlatSharp internally invokes `flatc` to do the IDL parsing.

One thing you can do as a short term workaround is to have one "index" FBS file:

```idl
include "A.fbs";
include "B.fbs";
...
include "Z.fbs";
```

It seems I should probably switch from command-line switches to using a configuration file to avoid the path-length limitations.

Regarding the original topic of this thread, I've created this [issue](https://github.com/google/flatbuffers/issues/8053) in the FlatBuffers repository to see if I can get some guidance. The short version is that `flatc` doesn't do a great job of telling me which files were explicitly passed in and which were included.

**Comment by duckdoom4** [comment]
Awesome stuff. Thanks for taking the time to help me with this.

In regards to the include thing. I think you might not need to know what files are included.

Can't we do something like:

```
var namespace = GetNamespaceFromFile()
var typeName = GetTypeNameFromFile(); // name of class or struct or enum etc.

string fullyQualifiedName = namespace + "." + typeName;

Map<string, FBSCodeString> typesMap;

If not typesMap contains fullyQualifiedName {
    Add to map
}
Else
{
  Type is already defined. Might want to produce an error if the source file doesn't match
}
```

**Comment by duckdoom4** [comment]
And maybe we could even give the end user some control over the compilation units by allowing multiple <FlatBuffer Input=""/> tags and adding an additional output file option.

For something along the lines of:

We have one large project, but we want to generate one set of flat buffers as ProjectA and another set as ProjectB. You might want this if you have conditional compilation. And right now, it would solve part of my problem by compiling into multiple units allowing shorter commands to be used.

But tbh, if the issue here is solved, I don't think we'd need this option anymore.

**Comment by jamescourtney** [comment]
I have a fix for this pending a bunch of test breaks.

There are two new MSBuild properties you can leverage:
```xml
<PropertyGroup>
    <!-- this goes in your shared library. This emits the class definitions, but no serializers -->
   <FlatSharpClassDefinitionsOnly>true</FlatSharpClassDefinitionsOnly>

    <!-- this goes in the consuming library. This triggers only processing 
            explicitly-passed input files. Serializers will be generated for included files, but no class definitions -->
   <FlatSharpInputFilesOnly>true</FlatSharpInputFilesOnly>
</PropertyGroup>

```

One big limitation is that I can't resolve different drive letters on Windows. Flatc doesn't tell me the drive letter, so I'm kind of up a creek in that regard.

**Comment by duckdoom4** [comment]
I think it's safe-ish to assume the drive letter is the same as the input file. No one in their right mind would put in absolute paths to includes in their .fbs

**Comment by jamescourtney** [comment]
Fixed in 7.2.0 -- let me know how it works for you!

**Comment by duckdoom4** [comment]
Awesome! Thanks for all the effort you put into helping us integrate it into our project!

I'll be testing everything first chance I get :)

**Comment by jamescourtney** [comment]
@duckdoom4  -- Please LMK if this is working as you expect. You should probably use FlatSharp 7.2.1 as it resolves the drive-letter issue.

**Comment by duckdoom4** [comment]
Sorry, didn't have much time yet. I tried to get things to work but didn't complete the update yet. So far everything seems to work with one exception, but that might be my mistake. I'll let you know when I can be certain

**Comment by duckdoom4** [comment]
@jamescourtney Hi there, I finally got time to test everything out properly. I am running into a small issue still though, but I think that's easy to solve. How did you intend the projects to be structured?

I now have: 
ClassLibrary called `pkNX.Structures.FlatBuffers.Shared`
With the following properties:
`
<PropertyGroup>
  <FlatSharpClassDefinitionsOnly>true</FlatSharpClassDefinitionsOnly>
</PropertyGroup>

<ItemGroup>
  <FlatSharpSchema Include="Schemas\**\*.fbs">
    <IncludePath>Schemas\</IncludePath>
  </FlatSharpSchema>
</ItemGroup>
`

ClassLibrary called `pkNX.Structures.FlatBuffers.Main`
With the following properties:
`
<ItemGroup>
  <ProjectReference Include="..\pkNX.Structures.FlatBuffers.Shared\pkNX.Structures.FlatBuffers.Shared.csproj" />
</ItemGroup>

<PropertyGroup>
  <FlatSharpDeserializers>GreedyMutable</FlatSharpDeserializers>
  <FlatSharpInputFilesOnly>true</FlatSharpInputFilesOnly>
</PropertyGroup>

<ItemGroup>
  <FlatSharpSchema Include="Schemas\**\*.fbs">
    <IncludePath>Schemas\</IncludePath>
    <IncludePath>..\pkNX.Structures.FlatBuffers.Shared\Schemas\</IncludePath>
  </FlatSharpSchema>
</ItemGroup>
`

This generates the following warning:
`.\pkNX.Structures.FlatBuffers.SWSH\..\FlatSharp.generated.cs(171497,21,171497,25): warning CS0436: The type 'AABB' in '.\pkNX.Structures.FlatBuffers.SWSH\..\FlatSharp.generated.cs' conflicts with the imported type 'AABB' in 'pkNX.Structures.FlatBuffers.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in '.\pkNX.Structures.FlatBuffers.SWSH\..\FlatSharp.generated.cs'.`

I can see that in both files it still generates the partial class for both projects in their `FlatSharp.generated.cs`. I'm guessing I just need to edit the project setup?

(Everything else is working wonderfully btw. Very happy with the new features :D)
